//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.0
//     from Assets/InputS/Aydens.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Aydens: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Aydens()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Aydens"",
    ""maps"": [
        {
            ""name"": ""key"",
            ""id"": ""e0c2152f-9c60-4280-a6b7-e11d0bc6c592"",
            ""actions"": [
                {
                    ""name"": ""UseKey"",
                    ""type"": ""Button"",
                    ""id"": ""3d017f75-42fb-4832-943f-2d0f459dcc37"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""14596ea6-2e65-4b7a-8a1e-663a6383fa6f"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // key
        m_key = asset.FindActionMap("key", throwIfNotFound: true);
        m_key_UseKey = m_key.FindAction("UseKey", throwIfNotFound: true);
    }

    ~@Aydens()
    {
        UnityEngine.Debug.Assert(!m_key.enabled, "This will cause a leak and performance issues, Aydens.key.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // key
    private readonly InputActionMap m_key;
    private List<IKeyActions> m_KeyActionsCallbackInterfaces = new List<IKeyActions>();
    private readonly InputAction m_key_UseKey;
    public struct KeyActions
    {
        private @Aydens m_Wrapper;
        public KeyActions(@Aydens wrapper) { m_Wrapper = wrapper; }
        public InputAction @UseKey => m_Wrapper.m_key_UseKey;
        public InputActionMap Get() { return m_Wrapper.m_key; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyActions set) { return set.Get(); }
        public void AddCallbacks(IKeyActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyActionsCallbackInterfaces.Add(instance);
            @UseKey.started += instance.OnUseKey;
            @UseKey.performed += instance.OnUseKey;
            @UseKey.canceled += instance.OnUseKey;
        }

        private void UnregisterCallbacks(IKeyActions instance)
        {
            @UseKey.started -= instance.OnUseKey;
            @UseKey.performed -= instance.OnUseKey;
            @UseKey.canceled -= instance.OnUseKey;
        }

        public void RemoveCallbacks(IKeyActions instance)
        {
            if (m_Wrapper.m_KeyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyActions @key => new KeyActions(this);
    public interface IKeyActions
    {
        void OnUseKey(InputAction.CallbackContext context);
    }
}
